// Enum defining API response codes.
export enum ApiCodeResponse {
  TEST = 'api.result.test',
  PAYLOAD_PARAM_IS_MISSING = 'api.error.payload-param-is-missing',
  COMMON_SUCCESS = 'api.success.common',
  COMMON_ERROR = 'api.error.common',
  ME_SUCCESS = 'api.success.me',

  SIGN_IN_SUCCESS = 'api.success.signin',
  SIGN_IN_ERROR = 'api.error.signin',
  SIGN_IN_PAYLOAD_USERNAME_MISSING = 'api.error.signin-payload-username-missing',
  SIGN_IN_PAYLOAD_USERNAME_LENGTH_ERROR = 'api.error.signin-payload-username-length',
  SIGN_IN_PAYLOAD_PASSWORD_MISSING = 'api.error.signin-payload-password-missing',
  SIGN_IN_PAYLOAD_SOCIAL_LOGIN_MISSING = 'api.error.signin-payload-social-login-missing',

  SIGNUP_ERROR = 'api.error.signup',
  SIGNUP_SUCCESS = 'api.success.signup',
  SIGNUP_PAYLOAD_USERNAME_IS_MISSING = 'api.error.signup-payload-username-is-missing',
  SIGNUP_PAYLOAD_USERNAME_LENGTH_ERROR = 'api.error.signup-payload-username-length',
  SIGNUP_PAYLOAD_PASSWORD_IS_MISSING = 'api.error.signup-payload-password-is-missing',
  SIGNUP_PAYLOAD_PASSWORD_LENGTH_ERROR = 'api.error.signup-payload-.password-length',
  SIGNUP_PAYLOAD_MAIL_IS_MISSING = 'api.error.signup-payload-mail-empty',
  SIGNUP_PAYLOAD_MAIL_INVALID = 'api.error.signup-payload-mail-invalid',

  USER_NOT_FOUND = 'api.error.user-not-found',
  USER_ALREADY_EXIST = 'api.error.user-already-exist',
  TOKEN_GEN_ERROR = 'api.error.token-generator',
  NO_TOKEN_FOUNDED = 'api.error.no-token-founded',
  TOKEN_EXPIRED = 'api.error.token-expired',
  CREDENTIAL_DELETE_ERROR = 'api.error.account-delete',
  CREDENTIAL_DELETE_SUCCESS = 'api.success.account-delete',
  PAYLOAD_IS_NOT_VALID = 'api.error.payload-is-not-valid',

  MEMBER_NOT_FOUND = 'api.error.member-not-found',
  MEMBER_DELETE_SUCCESS = 'api.success.member-delete',
  MEMBER_UPDATE_ERROR = 'api.error.member-update',
  MEMBER_UPDATE_SUCCESS = 'api.success.member-update',
  MEMBER_DELETE_ERROR = 'api.error.member-delete',
  MEMBER_LIST_ERROR = 'api.error.member-list',
  MEMBER_LIST_SUCCESS = 'api.success.member-list',
  MEMBER_CREATE_ERROR = 'api.error.member-create',
  MEMBER_CREATE_SUCCESS = 'api.success.member-create',
  MEMBER_PAYLOAD_FIRSTNAME_IS_NOT_STRING = 'api.error.member-payload-firstname-is-not-string',
  MEMBER_PAYLOAD_FIRSTNAME_LENGTH_ERROR = 'api.error.member-payload-firstname-length-error',
  MEMBER_PAYLOAD_LASTNAME_IS_NOT_STRING = 'api.error.member-payload-lastname-is-not-string',
  MEMBER_PAYLOAD_LASTNAME_LENGTH_ERROR = 'api.error.member-payload-lastname-length-error',
  MEMBER_PAYLOAD_BIRTHDATE_IS_NOT_VALID = 'api.error.member-payload-birthdate-invalid',
  MEMBER_PAYLOAD_GENDER_IS_NOT_VALID = 'api.error.member-payload-gender-invalid',
  MEMBER_PAYLOAD_MAIL_IS_NOT_VALID = 'api.error.member-payload-mail-invalid',
  MEMBER_PAYLOAD_MAIL_LENGTH_ERROR = 'api.error.member-payload-mail-length-error',
  MEMBER_PAYLOAD_PHONE_LENGTH_ERROR = 'api.error.member-payload-phone-length-error',
  MEMBER_PAYLOAD_ACTIVATION_CODE_LENGTH_ERROR = 'api.error.member-payload-activation-code-length-error',
  MEMBER_PAYLOAD_IBAN_LENGTH_ERROR = 'api.error.member-payload-iban-length-error',
  MEMBER_PAYLOAD_SUBSCRIPTION_NOT_VALID = 'api.error.member-payload-subscription-invalid',
  MEMBER_PAYLOAD_MEMBER_ID_MANDATORY = 'api.error.member-payload-member_id-mandatory',
  MEMBER_PAYLOAD_MEMBER_ID_LENGTH_ERROR = 'api.error.member-payload-member_id-length-error',
  MEMBER_PAYLOAD_ACTIVE_INVALID = 'api.error.member-payload-active-invalid',

  MEMBER_PLAN_NOT_FOUND = 'api.error.member-plan-not-found',
  MEMBER_PLAN_DELETE_SUCCESS = 'api.success.member-plan-delete',
  MEMBER_PLAN_DELETE_ERROR = 'api.error.member-plan-delete',
  MEMBER_PLAN_LIST_ERROR = 'api.error.member-plan-list',
  MEMBER_PLAN_LIST_SUCCESS = 'api.success.member-plan-list',
  MEMBER_PLAN_CREATE_ERROR = 'api.error.member-plan-create',
  MEMBER_PLAN_CREATE_SUCCESS = 'api.success.member-plan-create',
  MEMBER_PLAN_UPDATE_ERROR = 'api.error.member-plan-update',
  MEMBER_PLAN_UPDATE_SUCCESS = 'api.success.member-plan-update',
  MEMBER_PLAN_TYPE_INVALID = 'api.error.member-plan.type.invalid',
  MEMBER_PLAN_TITLE_MANDATORY = 'api.error.member-plan.title.mandatory',
  MEMBER_PLAN_TITLE_LENGTH_ERROR = 'api.error.member-plan.title.length-error',
  MEMBER_PLAN_DESCRIPTION_INVALID = 'api.error.member-plan.description.invalid',
  MEMBER_PLAN_PICTURE_LENGTH_ERROR = 'api.error.member-plan.picture.length-error',
  MEMBER_PLAN_PRICE_INVALID = 'api.error.member-plan.price.invalid',
  MEMBER_PLAN_PRICE_MANDATORY = 'api.error.member-plan.price.mandatory',
  MEMBER_PLAN_NB_MONTH_INVALID = 'api.error.member-plan.nb-month.invalid',
  MEMBER_PLAN_NB_MONTH_MANDATORY = 'api.error.member-plan.nb-month.mandatory',
  MEMBER_PLAN_PAYMENT_INVALID = 'api.error.member-plan.payment.invalid',
  MEMBER_PLAN_CUMULATIVE_INVALID = 'api.error.member-plan.cumulative.invalid',
  MEMBER_PLAN_FREQ_TRAINING_INVALID = 'api.error.member-plan.freq-training.invalid',
  MEMBER_PLAN_NB_TRAINING_INVALID = 'api.error.member-plan.nb-training.invalid',
  MEMBER_PLAN_ID_MANDATORY = 'api.error.member-plan.id.mandatory',
  MEMBER_SUBSCRIPTION_NOT_FOUND = 'api.error.member-subscription.not-found',
  MEMBER_SUBSCRIPTION_DELETE_ERROR = 'api.error.member-subscription.error',
  MEMBER_SUBSCRIPTION_LIST_ERROR = 'api.error.member-subscription-list.error',
  MEMBER_SUBSCRIPTION_CREATE_ERROR = 'api.error.member-plan-create-error',

  ADDRESS_NOT_FOUND = 'api.error.address-not-found',
  ADDRESS_DELETE_SUCCESS = 'api.success.address-delete',
  ADDRESS_UPDATE_ERROR = 'api.error.address-update',
  ADDRESS_UPDATE_SUCCESS = 'api.success.address-update',
  ADDRESS_DELETE_ERROR = 'api.error.address-delete',
  ADDRESS_LIST_ERROR = 'api.error.address-list',
  ADDRESS_LIST_SUCCESS = 'api.success.address-list',
  ADDRESS_CREATE_ERROR = 'api.error.address-create',
  ADDRESS_CREATE_SUCCESS = 'api.success.address-create',

  EXERCISE_DATA_NOT_FOUND = 'api.error.exercise-data-not-found',
  EXERCISE_DATA_DELETE_SUCCESS = 'api.success.exercise-data-delete',
  EXERCISE_DATA_UPDATE_ERROR = 'api.error.exercise-data-update',
  EXERCISE_DATA_UPDATE_SUCCESS = 'api.success.exercise-data-update',
  EXERCISE_DATA_DELETE_ERROR = 'api.error.exercise-data-delete',
  EXERCISE_DATA_LIST_ERROR = 'api.error.exercise-data-list',
  EXERCISE_DATA_LIST_SUCCESS = 'api.success.exercise-data-list',
  EXERCISE_DATA_CREATE_ERROR = 'api.error.exercise-data-create',
  EXERCISE_DATA_CREATE_SUCCESS = 'api.success.exercise-data-create',

  EXERCISE_TRAINING_NOT_FOUND = 'api.error.exercise-training-not-found',
  EXERCISE_TRAINING_DELETE_SUCCESS = 'api.success.exercise-training-delete',
  EXERCISE_TRAINING_UPDATE_ERROR = 'api.error.exercise-training-update',
  EXERCISE_TRAINING_UPDATE_SUCCESS = 'api.success.exercise-training-update',
  EXERCISE_TRAINING_DELETE_ERROR = 'api.error.exercise-training-delete',
  EXERCISE_TRAINING_LIST_ERROR = 'api.error.exercise-training-list',
  EXERCISE_TRAINING_LIST_SUCCESS = 'api.success.exercise-training-list',
  EXERCISE_TRAINING_CREATE_ERROR = 'api.error.exercise-training-create',
  EXERCISE_TRAINING_CREATE_SUCCESS = 'api.success.exercise-training-create',

  TRAINING_CIRCUIT_NOT_FOUND = 'api.error.training-circuit-not-found',
  TRAINING_CIRCUIT_DELETE_SUCCESS = 'api.success.training-circuit-delete',
  TRAINING_CIRCUIT_UPDATE_ERROR = 'api.error.training-circuit-update',
  TRAINING_CIRCUIT_UPDATE_SUCCESS = 'api.success.training-circuit-update',
  TRAINING_CIRCUIT_DELETE_ERROR = 'api.error.training-circuit-delete',
  TRAINING_CIRCUIT_LIST_ERROR = 'api.error.training-circuit-list',
  TRAINING_CIRCUIT_LIST_SUCCESS = 'api.success.training-circuit-list',
  TRAINING_CIRCUIT_CREATE_ERROR = 'api.error.training-circuit-create',
  TRAINING_CIRCUIT_CREATE_SUCCESS = 'api.success.training-circuit-create',

  WORKOUT_NOT_FOUND = 'api.error.workout-not-found',
  WORKOUT_DELETE_SUCCESS = 'api.workout-delete',
  WORKOUT_UPDATE_ERROR = 'api.workout-update',
  WORKOUT_UPDATE_SUCCESS = 'api.workout-data-update',
  WORKOUT_DELETE_ERROR = 'api.error.workout-delete',
  WORKOUT_LIST_ERROR = 'api.error.workout-list',
  WORKOUT_LIST_SUCCESS = 'api.success.workout-list',
  WORKOUT_CREATE_ERROR = 'api.error.workout-create',
  WORKOUT_CREATE_SUCCESS = 'api.success.workout-create',

  COLLECTIVE_TRAINING_NOT_FOUND = 'api.error.collective-training-not-found',
  COLLECTIVE_TRAINING_DELETE_SUCCESS = 'api.success.collective-training-delete',
  COLLECTIVE_TRAINING_UPDATE_ERROR = 'api.error.collective-training-update',
  COLLECTIVE_TRAINING_UPDATE_SUCCESS = 'api.success.collective-training-update',
  COLLECTIVE_TRAINING_DELETE_ERROR = 'api.error.collective-training-delete',
  COLLECTIVE_TRAINING_LIST_ERROR = 'api.error.collective-training-list',
  COLLECTIVE_TRAINING_LIST_SUCCESS = 'api.success.collective-training-list',
  COLLECTIVE_TRAINING_CREATE_ERROR = 'api.error.collective-training-create',
  COLLECTIVE_TRAINING_CREATE_SUCCESS = 'api.success.collective-training-create',

  PERSONNAL_TRAINING_NOT_FOUND = 'api.error.personnal-training-not-found',
  PERSONNAL_TRAINING_DELETE_SUCCESS = 'api.success.personnal-training-delete',
  PERSONNAL_TRAINING_UPDATE_ERROR = 'api.error.personnal-training-update',
  PERSONNAL_TRAINING_UPDATE_SUCCESS = 'api.success.personnal-training-update',
  PERSONNAL_TRAINING_DELETE_ERROR = 'api.error.personnal-training-delete',
  PERSONNAL_TRAINING_LIST_ERROR = 'api.error.personnal-training-list',
  PERSONNAL_TRAINING_LIST_SUCCESS = 'api.success.personnal-training-list',
  PERSONNAL_TRAINING_CREATE_ERROR = 'api.error.personnal-training-create',
  PERSONNAL_TRAINING_CREATE_SUCCESS = 'api.success.personnal-training-create',
}
