import { ApiOperationOptions } from '@nestjs/swagger';

/**
 * This file defines Swagger documentation options for various API operations.
 * It provides descriptive metadata for each endpoint, enhancing the API documentation
 * generated by Swagger. This includes summaries and descriptions for different
 * controller methods, which are used to create and manage user credentials, members,
 * member cards, ...
 */

/*------------------------------------------------------------------------------------------------------*/
/*------------------------------------------- AUTH -----------------------------------------------------*/
/*------------------------------------------------------------------------------------------------------*/

/*------------------------------------- CONTROLLER -----------------------------------------------------*/

export const AuthenticatedControllerSignIn: ApiOperationOptions = {
  summary: 'User Sign-In',
  description:
    'Authenticate a user using their credentials and return an authentication token.',
};

export const AuthenticatedControllerAdminSignIn: ApiOperationOptions = {
  summary: 'Admin Sign-In',
  description:
    'Authenticate an admin user using their credentials and return an authentication token.',
};

export const AuthenticatedControllerSignUp: ApiOperationOptions = {
  summary: 'User Sign-Up',
  description:
    'Register a new user and return an authentication token upon successful registration.',
};

export const AuthenticatedControllerRefresh: ApiOperationOptions = {
  summary: 'Refresh Authentication Token',
  description: 'Refresh the authentication token using a valid refresh token.',
};

export const AuthenticatedControllerMe: ApiOperationOptions = {
  summary: 'Get Current User Information',
  description: "Retrieve the current authenticated user's profile information.",
};

export const AuthenticatedControllerDelete: ApiOperationOptions = {
  summary: 'Delete Credential',
  description:
    'Delete a user credential by its ID and remove associated authentication tokens.',
};

export const AuthenticatedControllerLinkGoogleAccount: ApiOperationOptions = {
  summary: 'Link Google Account',
  description:
    'Method for linking a Google account to an existing user account.',
};

export const AuthenticatedControllerLinkFacebookAccount: ApiOperationOptions = {
  summary: 'Link Facebook Account',
  description:
    'Method for linking a Facebook account to an existing user account.',
};

export const AuthenticatedControllerLinkUsername: ApiOperationOptions = {
  summary: 'Link Username and Password',
  description:
    'Method for linking a username and password to an existing user account.',
};

/*--------------------------------------- ENTITY -------------------------------------------------------*/

export const credentialProperties = {
  credential_id: {
    description:
      'Unique identifier for the credential. Uses a custom transformer for serialization.',
    name: 'credential_id',
  },
  username: {
    description: 'Username for the credential',
    name: 'username',
  },
  password: {
    description:
      'Password for the credential, excluded from plain serialization',
    name: 'password',
  },
  facebook_hash: {
    description: 'Facebook hash associated with the credential',
    name: 'facebookHash',
  },
  google_hash: {
    description: 'Google hash associated with the credential',
    name: 'googleHash',
  },
  is_admin: {
    description: 'Flag indicating if the user is an admin',
    name: 'isAdmin',
  },
};

export const signInProperties = {
  social_login: {
    name: 'socialLogin',
    description: 'Indicates if the login is done through social networks',
  },
};

export const signUpProperties = {
  code_activation: {
    name: 'code_activation',
    description:
      'Activation code used to link an existing member to a credential',
  },
};

/*------------------------------------------------------------------------------------------------------*/
/*--------------------------------------- MEMBER -------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------------*/

/*------------------------------------- CONTROLLER -----------------------------------------------------*/

export const MemberControllerCreate: ApiOperationOptions = {
  summary: 'Create Member',
  description: 'Create a new member and store their details in the database.',
};

export const MemberControllerDetail: ApiOperationOptions = {
  summary: 'Get Member Details',
  description: 'Retrieve the details of a specific member by their ID.',
};

export const MemberControllerList: ApiOperationOptions = {
  summary: 'List All Members',
  description: 'Retrieve a list of all members stored in the database.',
};

export const MemberControllerUpdate: ApiOperationOptions = {
  summary: 'Update Member',
  description: 'Update the details of an existing member.',
};

export const MemberControllerDelete: ApiOperationOptions = {
  summary: 'Delete Member',
  description: 'Delete a specific member from the database by their ID.',
};

export const MemberControllerFilter: ApiOperationOptions = {
  summary: 'Filter Members',
  description:
    'Retrieve a list of members based on specific filtering criteria.',
};

/*--------------------------------------- ENTITY -------------------------------------------------------*/

/*------------------------------------------------------------------------------------------------------*/
/*------------------------------------- MEMBER CARD ----------------------------------------------------*/
/*------------------------------------------------------------------------------------------------------*/

/*------------------------------------- CONTROLLER -----------------------------------------------------*/

export const MemberCardControllerCreate: ApiOperationOptions = {
  summary: 'Create MemberCard',
  description:
    'Create a new member card and store its details in the database.',
};

export const MemberCardControllerDetail: ApiOperationOptions = {
  summary: 'Get MemberCard Details',
  description: 'Retrieve the details of a specific member card by its ID.',
};

export const MemberCardControllerList: ApiOperationOptions = {
  summary: 'List All MemberCards',
  description: 'Retrieve a list of all member cards stored in the database.',
};

export const MemberCardControllerUpdate: ApiOperationOptions = {
  summary: 'Update MemberCard',
  description: 'Update the details of an existing member card.',
};

export const MemberCardControllerDelete: ApiOperationOptions = {
  summary: 'Delete MemberCard',
  description: 'Delete a specific member card from the database by its ID.',
};

export const MemberCardControllerFilter: ApiOperationOptions = {
  summary: 'Filter MemberCards',
  description:
    'Retrieve a list of member cards based on specific filtering criteria.',
};

/*--------------------------------------- ENTITY -------------------------------------------------------*/

/*------------------------------------------------------------------------------------------------------*/
/*--------------------------------------- ADDRESS ------------------------------------------------------*/
/*------------------------------------------------------------------------------------------------------*/

/*------------------------------------- CONTROLLER -----------------------------------------------------*/

export const AddressControllerCreate: ApiOperationOptions = {
  summary: 'Create Address',
  description: 'Create a new address and store its details in the database.',
};

export const AddressControllerDetail: ApiOperationOptions = {
  summary: 'Get Address Details',
  description: 'Retrieve the details of a specific address by its ID.',
};

export const AddressControllerList: ApiOperationOptions = {
  summary: 'List All Addresses',
  description: 'Retrieve a list of all addresses stored in the database.',
};

export const AddressControllerUpdate: ApiOperationOptions = {
  summary: 'Update Address',
  description: 'Update the details of an existing address.',
};

export const AddressControllerDelete: ApiOperationOptions = {
  summary: 'Delete Address',
  description: 'Delete a specific address from the database by its ID.',
};

export const AddressControllerFilter: ApiOperationOptions = {
  summary: 'Filter Addresses',
  description:
    'Retrieve a list of addresses based on specific filtering criteria.',

  /*--------------------------------------- ENTITY -------------------------------------------------------*/
};
